#!/bin/sh

IFS="
"

for file in `find . -maxdepth 1 | sort`; do

  file=`basename "$file"`

  result1="`echo $file \\
   | sed -e 's/(//' \\
   | sed -e 's/)//' \\
   | tr '[A-Z]' '[a-z]' \\
   | sed -e 'y/АБВГҐДЕЄЖЗИІЇЙКЛМНОПРСТУФХЦЧШЩЬЮЯЁЪЫЭЎ/абвгґдеєжзиіїйклмнопрстуфхцчшщьюяёъыэў/' \\
   | tr ' ' '_' \\
   | tr -d \' \\
   | tr -d \, \\
   | sed -e 's/_\./\./' \\
   | sed 's/\._/_/' \\
   | sed -e 's/_-_/-/' \\
   | sed -e 's/--_/-/' \\
   | sed -e 's/[\!\+]//' \\
   | sed -e 's/\&/and/' \\
   | perl -ne '$_=~s/^(\d\d)_/$1-/; print \"$_\n\"' \\
   | sed -e 's/_-_/-/'`"

  if [ -n "$1" ]; then
    result2="`echo $result1 | sed -e \"s/$1//\"`"
  else
    result2="$result1"
  fi

  if [ "$file" != "$result2" ]; then
    echo "$result2"
    mv "$file" "$result2"
  fi

done

